# Generated by Django 6.0.6 on 2026-07-15 16:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[300, 300], upload_to='social_post_images/'),
        ),
    ]
