# Generated by Django 6.0.6 on 2026-07-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_contact_user_following_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created']},
        ),
    ]
