# Generated by Django 6.0.6 on 2026-07-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_post_total_likes_post_social_post_total_l_b22ce0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
